### ISSUE TITLE
Updated analysis: BS_5BMNK8SY assigned 2 MB subtypes

### ISSUE THREAD

**Issue by kgaonkar6** [AlexsLemonade/OpenPBTA-analysis#1085]
#### What analysis module should be updated and why?
[molecular_subtyping_MB](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-MB)
BS_5BMNK8SY has 2 subtypes from matching with 2 different RNA-Seq with sample_id==7316-14

Kids_First_Biospecimen_ID | sample_id | aliquot_id | Kids_First_Participant_ID | cohort_participant_id | previous_parent_aliquot_id | parent_aliquot_id | molecular_subtype | pathology_diagnosis | pathology_free_text_diagnosis | integrated_diagnosis | harmonized_diagnosis
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BS_5BMNK8SY | 7316-14 | 654436 | PT_M0AP3Z15 | C19803 | 7316-14-T-8725.WGS | 7316-14-T-8725.WGS | MB, To be classified | Medulloblastoma | medulloblastoma | NA | Medulloblastoma
BS_5BMNK8SY | 7316-14 | 654436 | PT_M0AP3Z15 | C19803 | 7316-14-T-8725.WGS | 7316-14-T-8725.WGS | MB, Group4 | Medulloblastoma | medulloblastoma | Medulloblastoma, group 4 | Medulloblastoma, group 4
BS_QEYPFYHD | 7316-14 | 654201 | PT_M0AP3Z15 | C19803 | 7316-14-T-8725.RNA-Seq | 7316-14-T-8725.RNA-Seq | MB, To be classified | Medulloblastoma | medulloblastoma | NA | Medulloblastoma
BS_Z7PKVY9J | 7316-14 | 1030649 | PT_M0AP3Z15 | C19803 | 7316-14-T-8711.RNA-Seq | 7316-14-T-8711.RNA-Seq | MB, Group4 | Medulloblastoma | medulloblastoma | Medulloblastoma, group 4 | Medulloblastoma, group 4
BS_ZH666SJW | 7316-14 | 612624 | PT_M0AP3Z15 | C19803 | 7316-14-N-8710.WGS | 7316-14-N-8710.WGS | NA | NA | NA | NA | NA

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We can use the parent_aliqout_id can help match BS_5BMNK8SY with BS_QEYPFYHD, however we will have to remove the suffix (".WGS" and ".RNA-Seq") to match the "7316-14-T-8725" parent_aliquot_id between the DNA and RNA samples at this step. 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b65de24c266706e46ae714b922e30c7e14883942/analyses/molecular-subtyping-MB/03-compare-classes.Rmd#L74-L75

#### What input data should be used? Which data were used in the version being updated?
pbta-histologies-base.tsv
analyses/collapse-rnaseq/results/pbta-gene-expression-rsem-fpkm-collapsed.polya.rds
analyses/collapse-rnaseq/results/pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds

**Comment by komalsrathi** [comment]
@kgaonkar6 I am slightly confused - molecular subtyping is done on the RNA samples only. The DNA sample `BS_5BMNK8SY` is associated with two different RNA samples: `BS_Z7PKVY9J` and `BS_QEYPFYHD`. This is the output of the classification is below:

```
> dat %>% filter(Kids_First_Biospecimen_ID_DNA == "BS_5BMNK8SY")
  Kids_First_Participant_ID sample_id Kids_First_Biospecimen_ID_DNA Kids_First_Biospecimen_ID_RNA
1               PT_M0AP3Z15   7316-14                   BS_5BMNK8SY                   BS_QEYPFYHD
2               PT_M0AP3Z15   7316-14                   BS_5BMNK8SY                   BS_Z7PKVY9J
     molecular_subtype
1 MB, To be classified
2           MB, Group4
```

The reason for this discrepancy is because we are using MM2S as an additional classifier and using the consensus between our medulloPackage (our classifier) and MM2S. MM2S is classifying BS_QEYPFYHD as SHH and BS_Z7PKVY9J as Group4 whereas medulloPackage is classifying both RNA samples as Group4. Because we don't have a consensus for BS_QEYPFYHD, the final classification is different than BS_Z7PKVY9J. 

I am not aware who generated the table that you attached but that is not the output of the module, this is: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-MB/results/MB_molecular_subtype.tsv 

Am I missing anything?

**Comment by komalsrathi** [comment]
> My main issue is that the sample BS_5BMNK8SY should have 1 subtype but currently has 2 `MB, To be classified` and `MB, Group4` because it matches to 2 RNAseq ids when we only use "sample_id" to match.

From the molecular subtype module perspective, this can only be resolved if we used one of the classifiers and not the consensus. Or if we only use one RNA sample per DNA for subtyping. 

cc: @jharenza

**Comment by komalsrathi** [comment]
@kgaonkar6 can you close this if this is resolved? (I don't have permissions, thank you!)

**Comment by jharenza** [comment]
Closing with #1096
