### ISSUE TITLE
Planned data release: V5

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#121]
Currently planned for 24-Sept-2019

Planned addition + changes from @jharenza :
* Vardict - VEP annotated MAF (related: #103)
* Lancet – VEP annotated MAF (related: #103)
* Updated arriba fusion file (related: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/92#discussion_r324873300)
* RSEM gene level count matrix
* RSEM transcript level count matrix (related: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/14#issuecomment-533527194)
* Updated lumpy file - to fix T/N columns (related: https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/27#issuecomment-533251123)

**Comment by jaclyn-taroni** [comment]
@jharenza we may want to split the expression data files up based on the RNA library based on @jashapiro 's results on #120 - notebook [here](https://shapbio.me/OutputShare/01-selection-strategies.nb.html)

**Comment by jharenza** [comment]
ok - separate RDS files for FPKM from each algorithm, as well as counts?

**Comment by jaclyn-taroni** [comment]
That seems like it would be the most flexible way to go as far as downstream options if it's straightforward to do.

**Comment by jharenza** [comment]
Ok, yeah once we merge, I can just separate into two RDS files.

**Comment by jharenza** [comment]
> @jharenza we may want to split the expression data files up based on the RNA library based on @jashapiro 's results on #120 - notebook [here](https://shapbio.me/OutputShare/01-selection-strategies.nb.html)

Thinking about this again - would it be easier for those working on RNA to do this separation using the clinical file? I ask because many other analyses using these files may have to re-combine (eg - fusion workflow will use both stranded and polyA and if we look for CNV deletion evidence on the basis of RNA expression <1 FPKM, we would recombine these files). I agree we should not cluster/perform certain analyses together, but trying to think of what makes more sense - for those specific analyses tainted by strand to separate or for us to separate all now and make sure other users know they may have to re-combine. Thoughts?

**Comment by jashapiro** [comment]
I would still support separating the files, and having the users combine them as needed. This means that the user will have to explicitly acknowledge that they are combining two different data sets, and may give a slight bit of pause to consider whether that is appropriate. For example, the meaning of FPKM < 1 is likely to be different in the two data sets, and the using the same cutoffs may not be appropriate.

**Comment by jharenza** [comment]
@jashapiro - makes sense! We will plan on separating them then.

**Comment by jharenza** [comment]
@cgreene @jaclyn-taroni @jashapiro - we have the CHANGELOG and all files except the transcript counts file staged and ready to go - that merge is taking longer than anticipated, so @yuankunzhu will either create the PR without that file later tonight and add tomorrow or just create the whole PR tomorrow morning.
