### ISSUE TITLE
Updated analysis: oncoprint counts for manuscript

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#1252]
#### What analysis module should be updated and why?

Related to [MS PR #199](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/199), we need to create a notebook in `oncoprint-landscape` module tabulating certain counts that are slated to appear in the manuscript. The results in this notebook can then be used to populate the respective manuscript sections.

**Comment by jharenza** [comment]
Thanks for opening this @sjspielman! 

I think this addition might be a bit complicated. 

Since we highlight specific cancer group statistics in the manuscript, the goal would be to generate cancer_group specific tables for `*primary_only_*_oncoprint_summary_n.tsv` files. This would entail creating maf subset files and output tables for every cancer group that is represented in the oncoprints currently, including those in the supplemental oncoprint.

Would we want to make a new shell script and notebook for this since it will add a lot to the current workflow?

**Comment by jaclyn-taroni** [comment]
I will pick this up and make the determination about how to implement it along the way

**Comment by sjspielman** [comment]
Closed by #1266
