### ISSUE TITLE
Figure S2 H-I are no longer ordered by median TMB 

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#1563]
TMB plots for S2 H-I became unordered when previously ordered by ascending median TMB, so I think these should be updated :(

Note: I don't think this blocks converting the manuscript to a document for distribution.

**Comment by sjspielman** [comment]
Since I've worked on them, these plots have never been ordered by median TMB, but instead by frequency of cancer group. 

This is set in these lines of code - 
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b6a006d2071bfd41608ec61bc9958432e0427c49/figures/scripts/supp-tmb-compare-panels.R#L148-L156

Based on git history, this script has always produced plots ordered by cancer group frequency - https://github.com/AlexsLemonade/OpenPBTA-analysis/commit/996a0011b60b42772342b16167fa3656a730f110#diff-0e7567890c35e6fcfd9ee4fbdc38355de36ae4c1a4e50c789d0a2284737b6fcd

**Comment by jaclyn-taroni** [comment]
It's a reversion _in a way_ – just wanted to add some additional context. We used to make TMB panels in this deprecated figure script:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b6a006d2071bfd41608ec61bc9958432e0427c49/figures/scripts/deprecated/mutational-landscape.R#L92-L130

Which uses this function that _does_ order by median:

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/b6a006d2071bfd41608ec61bc9958432e0427c49/analyses/tmb-compare/util/cdf-plot-function.R#L85-L91

**Comment by sjspielman** [comment]
I see, thanks for context @jaclyn-taroni!

This should be fairly quick to update either way, so I can start working on it.
