### ISSUE TITLE
Re-upload underlying figure data to Zenodo

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#1744]
Because: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1743

**Comment by sjspielman** [comment]
I checked that all other CSV files are properly delimited, and #1743 appears to be the only thing to fix.

**Comment by sjspielman** [comment]
And https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1751.

> I checked that all other CSV files are properly delimited,

I did this by reading everything all the CSVs in with `readr::read_csv()`, and I've since learned that was _not the right approach._ `readr` has no problem figuring out extra `\n` in the middle of lines (is this a bug or a feature? i'm on the fence!), but other platforms likely will not like this! I've now manually looked over every CSV and feel much more convinced that this additional fix in #1751 takes care of the the only other problematic file, but if someone else wants to peek around I will not argue...

**Comment by jashapiro** [comment]
> And #1751.
> 
> > I checked that all other CSV files are properly delimited,
> 
> I did this by reading everything all the CSVs in with `readr::read_csv()`, and I've since learned that was _not the right approach._ `readr` has no problem figuring out extra `\n` in the middle of lines (is this a bug or a feature? i'm on the fence!), but other platforms likely will not like this! I've now manually looked over every CSV and feel much more convinced that this additional fix in #1751 takes care of the the only other problematic file, but if someone else wants to peek around I will not argue...

I think removing newlines is good and fine, but having a newline in a CSV is pretty common, and I would expect most readers to handle it just fine (as long as the line is quoted). https://stackoverflow.com/questions/566052/can-you-encode-cr-lf-in-into-csv-files

**Comment by jaclyn-taroni** [comment]
DOI: 10.5281/zenodo.7877739
