### ISSUE TITLE
Question on Proposing a Multi-Step Analysis

### ISSUE THREAD

**Issue by GeoffLyle** [AlexsLemonade/OpenPBTA-analysis#188]
Hi all,

This is a question on proposing a multi-step analysis.  Our team has a plan to perform a gene level outlier analysis on the ribodeplete (stranded) samples.  However, there are several prior steps to reaching this point, which will generate artifacts of their own.

Since these artifacts will be used as inputs to the next steps of the analysis:
Should we propose a single analysis with multiple steps or multiple analyses made up of single steps (i.e. 1 issue with multiple steps or 2+ issues of smaller steps)?

Since the next steps of our analysis will depend on the outcomes of the previous steps:
Should we propose a single analysis, get feedback on the proposal and results, and update the issue when are ready to move on to the next step or should we propose all steps of our analysis and discuss each section as it occurs?

Thanks!

**Comment by jaclyn-taroni** [comment]
Hi @GeoffLyle, welcome! My inclination would be to file a single issue outlining all of the steps so folks can comment on the plan as whole. Then, each step/section should correspond to a single pull request. 

The [pull request template](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/.github/PULL_REQUEST_TEMPLATE.md) includes sections for soliciting specific feedback and reporting results, so that can help facilitate discussion around specific steps as they come in. 

How does that sound?

**Comment by GeoffLyle** [comment]
@jaclyn-taroni Sounds straightforward.  We will put together our proposal in a single issue.  If we have any other questions during the process we will add them to this ticket.

**Comment by cgreene** [comment]
Since this is addressed and the other issue is filed, I'm going to go ahead and close it now. Thanks!
