### ISSUE TITLE
Possible refactor: `snv-callers`

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#201]
We should take a moment to re-evaluate the overall structure of the [`snv-callers`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers) module to see if there are improvements that can be made and what the scope for those would be. We can take a look early next week.

**Comment by cansavvy** [comment]
**Things I'm noticing so far:**
- Some of the plots should be restructured for accommodating the full dataset. 
   - Turn VAF correlation plot into a hexplot
   - Save histology legend separately
-  VAF of caller combinations doesn't save correctly to its png
- Some output messages are printing out the wrong file.path though they are saving to the correct file path. 

**Optimization question*
- Would be nice to have it print out an overall numbers report somewhere. As opposed to digging through the progress messages. 
- How do we avoid saving and re-reading the really big VAF files? i.e. VarDict and the master VAF file. Maybe make option where 03-merge_caller can source 04 directly and skip the save/load steps.

**Comment by cansavvy** [comment]
### Changes to make to SNV caller pipeline

**Plot Aesthetic Changes:** 
- Some of the plots should be restructured for accommodating the full dataset. 
   - Turn VAF correlation plot into a hexplot
   - Save histology legend separately for `compare_snv_callers.Rmd` plot. 
   -  VAF of caller combinations doesn't save correctly to its png

**Serious flaw**
- Get rid of `opt$output` 2x normalization flaw. 

**Memory saving changes: **
01-calculate_tmb_vaf.R and 03-merge_callers are the two biggest memory hogs look for opportunities here. 
- Make option where 03-merge_caller can source 04 directly and skip the save/load steps.  
- Change merging and joining steps to use `dbplyr` so its using SQL and uses less memory. 
- As opposed to making mutation_id it's own column, can use a join function that functionally matches callers by the columns that make up `mutation_id.`
- Reduce amount of intermediary files that have to be written and read in again (this is a big use of memory).

**Comment by cansavvy** [comment]
@jashapiro Let me know if you have further ideas for reducing the memory usage of this pipeline.

**Comment by jashapiro** [comment]
As you note, a big memory hog is going to be reading and writing large tables. One way to handle this may be to use the [arkdb package](https://github.com/ropensci/arkdb) (Note that despite instructions, it is available on CRAN). 

If you store intermediate result tables in the db file, you will not have to save and load the files, which will allow transmission of results between scripts, without necessarily having to have one script source another.

**Comment by cansavvy** [comment]
Nice! I will look into arkdb then!

**Comment by cansavvy** [comment]
My refactoring plan has included making the `opt$file_format` option into an optional `opt$file_save` option, where the default is that the data are not saved to RDS or TSV files unless you specify with that option. Otherwise, all data is just saved to the SQLite file in order to speed up the process. What do you think of this plan @jashapiro? I guess my thought is that I could see an instance where someone would want one of the intermediary files in a more "normal" file format so they could use it. But will this make it too confusing?

**Comment by jashapiro** [comment]
I think that makes sense. Is there a reason people will want the intermediate files for anything but debugging?

**Comment by cansavvy** [comment]
> I think that makes sense. Is there a reason people will want the intermediate files for anything but debugging?

Um mostly debugging? Maybe I should just get rid of the whole thing? IDK.

**Comment by cansavvy** [comment]
In my tackling of Tumor Mutation Burden and comparing to TCGA, I've realized it would probably be useful to have the SNV pipeline make two TMB files: One calculated with all mutations and another calculated with coding mutations only.

**Comment by cansavvy** [comment]
## Update: 
@jashapiro and I made a plan for the refactoring of snv-caller consensus pipeline so that it can be less memory intensive. 

#### Major changes: 
- `01-load-db.py` will create an SQL database that the other scripts use (@jashapiro is working on this). 
- `02-merge.R`: Will have the calculating functions of `01-calculate_tmb_vaf.R` and merging functions of `03-merge-caller.R` which will perform the merging with a SQL command chunk. 
- `03-eval `: will create the output reports and calculate TMB for each sample.

#### Scripts that will remain *relatively* unchanged: 
snv-callers/00-set_up.R
snv-callers/compare_snv_callers_plots.Rmd

@jashapiro Please fill in details and correct me where I am wrong.

**Comment by jaclyn-taroni** [comment]
@jashapiro how about this one, can it get closed?

**Comment by jashapiro** [comment]
Codewise, I think so, but I would check with @cansavvy. But also, once the Readme is updated?

**Comment by jaclyn-taroni** [comment]
I'm going to close it because I also got the impression that it has been taken care of codewise and file a ticket focused specifically on documentation. We can reopen if needed.
