### ISSUE TITLE
[IDEA / DISCUSSION] Subset reference FASTA file for download in CI

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#281]
The data download step with the addition of the reference files has run in CI a few times now. The fastest that has gone has been over 9 minutes. This could be a major pain point for contributors. 

@jashapiro brought up the idea of having subset reference and annotation files for the specific purpose of CI. The issue title is about the FASTA file because that is larger and therefore more problematic and no analysis module uses it at the moment. 

##### Notes

* The first step in this process would be generating the subset reference and/or annotation files.
* I'm currently thinking that the logic in `download-data.sh` would be based on if `$RELEASE` was equal to `testing`.

**Comment by jashapiro** [comment]
The easiest thing would probably be to just download a single chromosome for CI, such as 
ftp://ftp.ensembl.org//pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.21.fa.gz 

This could cause problems with some analysis scripts, of course, but since none currently use these files, perhaps the pain would be minimal. 

On the other hand... if `BSgenome.Hsapiens.UCSC.hg38` is already installed as part of the docker image, can we take advantage of that in any way? Pull out the fasta files as part of CI for those that might need it?

**Comment by jaclyn-taroni** [comment]
> On the other hand... if BSgenome.Hsapiens.UCSC.hg38 is already installed as part of the docker image, can we take advantage of that in any way? Pull out the fasta files as part of CI for those that might need it?

Can you say a bit more about this @jashapiro?

**Comment by jashapiro** [comment]
Sure. With what is already in the docker container, rather than downloading anything in the CI file, we could run a little R script like: 
```
BSgenome::export(BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38, "genome.fasta")
```
to export a fasta file.

We would not want to do this for the default, as it assumes R and `BSgenome` packages are installed, which can not be guaranteed if running outside of the Docker image.
