### ISSUE TITLE
Documentation: Descriptions of all files in data/

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-analysis#334]
The data release itself should contain a detailed README describing each file (where was it obtained and/or which script created it, which analyses is it used for, etc).

**Comment by jharenza** [comment]
Hi @sjspielman! First, welcome to the project!

We currently have a `CHANGELOG.md` file accompanying all of the data releases, which points the user to the tickets explaining what the new files are/why they were updated. Did you want to see more information than this?

**Comment by jaclyn-taroni** [comment]
@sjspielman is the [Data Formats section](https://github.com/AlexsLemonade/OpenPBTA-analysis#data-formats) of the repository README closer to what you are looking for? I am considering reformatting that such that there are sections for the files that are the output of various callers vs. _derived_ files (e.g., consensus files) that can be directly tied to a specific analysis module. It would be great to get your feedback on the Data Formats section because I think it will help inform the README that goes in the data release. Thanks!

**Comment by sjspielman** [comment]
The section of the README pointed out by @jaclyn-taroni is more what I was thinking of - it's currently really nice for a general description of what types of files one might find, so I'm thinking a sort of "merged version" of this info plus what is recorded in the `CHANGELOG.md`. This will reduce the amount of time new contributors (and current contributors who are coming back to analyses later..) need to spend pouring through links to figure out the specifics of each individual data file. I can start to put some documentation together for this as well, collating all the existing information into a central, single file describing all the data at once!

**Comment by jaclyn-taroni** [comment]
Thank you @sjspielman !

**Comment by jaclyn-taroni** [comment]
Closed via #336. If we find that it's insufficient as we release v12, we can reopen.
