### ISSUE TITLE
.gitignore skips data file

### ISSUE THREAD

**Issue by yuankunzhu** [AlexsLemonade/OpenPBTA-analysis#41]
somehow the `.gitignore` file keeps ignoring changes in `data/` path, i saw you @cgreene only skips the DS_Store file, not sure what happened. I ended up using `git add -f` for force adding my commits.

**Comment by cgreene** [comment]
Hi @yuankunzhu - we were keeping the data folder empty so that we could expect to safely download in there without overwriting anything. We also added it to the gitignore so that we didn't have people accidentally committing files to the directory. I'm going to close this issue now. I've added some additional requests to #42 to get this to align with what we are hoping to fill in.
