### ISSUE TITLE
Annotated CNVkit data no longer shows SMARCB1 deletions in ATRT

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#473]
Context is rerunning the `molecular-subtyping-ATRT` module as part of #462.

#### What data file(s) does this issue pertain to?

`analyses/focal-cn-file-preparation/cnvkit_annotated_cn_autosomes.tsv.bz2` in the repo, not in the data release.

#### What release are you using?

The file was generated using `release-v13-20200116`

#### Put your question or report your issue here.

There are no longer _SMARCB1_ losses noted for the majority of ATRT samples since #452. You can see a notebook comparing the old annotated CNVkit file to the new CNVkit file here: https://jaclyn-taroni.github.io/openpbta-notebook-concept/segment-to-gene-mapping.nb.html

I assume that our finding of overlaps or filtering is more restrictive now. Here are a few thoughts as to why:

* Using the CDS BED file -- CDS should be more restrictive than exons
* Filtering based on cytoband (I don't think this is the major issue)
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/78bba86523e150789b3929ff01bac129b689f3f7/analyses/focal-cn-file-preparation/01-prepare-cn-file.R#L92
* Using `findOverlaps`: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/78bba86523e150789b3929ff01bac129b689f3f7/analyses/focal-cn-file-preparation/01-prepare-cn-file.R#L84
  instead of `mergeByOverlaps`: https://github.com/jaclyn-taroni/OpenPBTA-analysis/blob/fa214291713575be7fd20c92374b268870f4173f/analyses/focal-cn-file-preparation/01-prepare-cn-file.R#L82

It was previously suggested (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/182#discussion_r340587968) to use _SMARCB1_ losses in ATRT to check if things were as expected.

As a side note, there are "duplicate" rows because of how the arm values were joined, e.g., there is information for every arm joined to a gene, not just the relevant arm. It makes sense to look into and try to address this at the same time.

**Comment by cansavvy** [comment]
@cbethell and I investigated this a bit this afternoon. We feel confident that the the difference here is the CDS versus the exons, however because of how large all these files are we have been having troubles more definitively pin pointing the loss of SMARC because our computers crash locally when we try to run this with `GenomicRanges` in R. 

Here's our plan: 

- @cbethell is going to do an experiment with just the SMARCB1 data and compare what happened to its data with the `txdb` derived exon data, the CDS filtered file, and the exons filtered file. Because of the R memory hogging, she's just going to look at SMARCB1's fate for this process. She'll also do second step of filtering with the cytoband data if this first step doesn't automatically answer the question. 
- @cansavvy is to going try to tackle the memory R hogging problem by trying to convert some of these initial steps to something done by BEDtools. 
- Whichever of the two of us gets done with their respective task first is then going to try to figure out why the arms are being duplicated in the final result. I suspect this has something to do with the `tidyverse` wrangling steps and something going out of order or not doing what we think it's doing.
