### ISSUE TITLE
Updates in v16 for pbta-histologies.tsv

### ISSUE THREAD

**Issue by allisonheath** [AlexsLemonade/OpenPBTA-analysis#637]
#### What data file(s) does this issue pertain to?

pbta-histologies.tsv

#### What release are you using?

v16

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.

N/A - or this is what this ticket is trying to discern.

#### Put your question or report your issue here.

For v16 we have revamped how this file is generated so that it is coming from source databases versus carrying over the data from previous versions. The original data pull for OpenPBTA is over six months old now and during that time the CBTTC and PNOC operations team have been doing an in-depth QC process of this data. This means that there are quite a few values will be updated. Fortunately, many of these are going from unknown to known values. However, there are also actual changes of values as well.

This ticket is to enumerate those changes, get feedback on what analyses they might impact. Additionally, to determine if should rerun any of the subtyping or other analyses that get put into this file for v16. If we do, the order of operations of how that's done if we want it all to be in v16.

**Comment by allisonheath** [comment]
Initial summary of demographic changes:

| # Updates | Field | 
| ---------- |-------| 
| 20 | reported_gender | 
| 796 | race | 
| 398 | ethnicity |

**Comment by jaclyn-taroni** [comment]
Hi @allisonheath and @baileyckelly, of the demographic changes listed above, I don't expect any of those to change the logic or labels in the molecular subtyping modules. However, I do expect that the tabular data generated in those modules to change. That being said, the _idea_ of rerunning molecular subtyping modules, in particular, prior to a final release and then updating the clinical file with any changes for the final release is appealing. 

I think our ability to automate this is going to be somewhat limited because we made a choice to opt for a series of notebooks to document _scientific decision making_ (for example, What does it mean to have a _TP53_ mutation - does it have to be coding?), rather than build any kind of classification system.

Of the other analyses, [`sex-prediction-for-RNASeq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/5f2468daf2756a62c7d4615a7660b0a52e5ad135/analyses/sex-prediction-from-RNASeq) will need to be re-run with the changes in `reported_gender`.

A more general question about rerunning steps pre-release (that we can break into its own issue) is how to approach the [analysis files that get included in the data release](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/doc/data-formats.md#analysis-files) such as the fusion files, GISTIC, etc. which are sometimes a release behind.

**Comment by jaclyn-taroni** [comment]
I believe this was addressed via the v17 release (#764)
