### ISSUE TITLE
Remove any R package installation from notebooks or scripts, especially with BiocManager

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenPBTA-analysis#690]
Context: #689 - which is adding a script to specifically install Bioconductor packages on the project Docker container.

Having logic that checks whether or not a package is installed and if not installs it is reasonable if someone were to run an analysis outside the Docker container. But if we were to miss something in the Docker image and then run an analysis it could end up unpinning versions (as discovered on the journey of #684). So, we should remove any package installation from notebooks or scripts, especially any installation via `BiocManager`.

Here's a list from @sjspielman:

```
focal-cn-file-preparation/04-prepare-cn-file.R:  install.packages("BiocManager")
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("GenomicRanges", update = FALSE)
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("IRanges", update = FALSE)
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("annotatr", update = FALSE)
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene", update = FALSE)
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("org.Hs.eg.db", update = FALSE)
focal-cn-file-preparation/04-prepare-cn-file.R:  BiocManager::install("AnnotationDbi", update = FALSE)
gene-set-enrichment-analysis/01-conduct-gsea-analysis.R:## Load and/or install libraries ##
gene-set-enrichment-analysis/01-conduct-gsea-analysis.R:  install.packages("msigdbr")
gene-set-enrichment-analysis/01-conduct-gsea-analysis.R:  install.packages("BiocManager")
gene-set-enrichment-analysis/01-conduct-gsea-analysis.R:  BiocManager::install("GSVA")
molecular-subtyping-ATRT/02-ATRT-molecular-subtyping-plotting.R:  install.packages("ComplexHeatmap")
molecular-subtyping-ATRT/02-ATRT-molecular-subtyping-plotting.R:  install.packages("matrixStats")
molecular-subtyping-ATRT/02-ATRT-molecular-subtyping-plotting.R:  install.packages("ggfortify")
oncoprint-landscape/01-plot-oncoprint.R:  install.packages("BiocManager")
oncoprint-landscape/01-plot-oncoprint.R:  BiocManager::install("maftools")
cnv-chrom-plot/gistic_plot.Rmd:  install.packages("BiocManager")
cnv-chrom-plot/gistic_plot.Rmd:  BiocManager::install("ggbio")
cnv-comparison/01-cnv-comparison-plotting.Rmd:  install.packages("BiocManager")
cnv-comparison/01-cnv-comparison-plotting.Rmd:  BiocManager::install("GenVisR")
cnv-comparison/01-cnv-comparison-plotting.Rmd:  install.packages("cowplot")
molecular-subtyping-ATRT/01-ATRT-molecular-subtyping-data-prep.Rmd:  install.packages("DT")
molecular-subtyping-ATRT/01-ATRT-molecular-subtyping-data-prep.Rmd:  install.packages("htmlwidgets")
mutational-signatures/mutational_signatures.Rmd:  BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
mutational-signatures/mutational_signatures.Rmd:  install.packages("deconstructSigs")
mutect2-vs-strelka2/01-set-up.Rmd:    install.packages("BiocManager")
mutect2-vs-strelka2/01-set-up.Rmd:  BiocManager::install("maftools")
mutect2-vs-strelka2/01-set-up.Rmd:  install.packages("hexbin")
mutect2-vs-strelka2/01-set-up.Rmd:  install.packages("R.utils")
mutect2-vs-strelka2/02-analyze-concordance.Rmd:  install.packages("hexbin")
mutect2-vs-strelka2/02-analyze-concordance.Rmd:  devtools::install_github("clauswilke/colorblindr")
mutect2-vs-strelka2/02-analyze-concordance.Rmd:  install.packages("R.utils")
mutect2-vs-strelka2/02-analyze-concordance.Rmd:  install.packages("VennDiagrams")
snv-callers/compare_snv_callers_plots-tcga.Rmd:  install.packages("ggupset", repos = "http://cran.us.r-project.org")
snv-callers/compare_snv_callers_plots-tcga.Rmd:  install.packages("UpSetR", repos = "http://cran.us.r-project.org")
snv-callers/compare_snv_callers_plots-tcga.Rmd:  install.packages("GGally", repos = "http://cran.us.r-project.org")
snv-callers/compare_snv_callers_plots.Rmd:  install.packages("ggupset", repos = "http://cran.us.r-project.org")
snv-callers/compare_snv_callers_plots.Rmd:  install.packages("UpSetR", repos = "http://cran.us.r-project.org")
snv-callers/compare_snv_callers_plots.Rmd:  install.packages("GGally", repos = "http://cran.us.r-project.org")
snv-callers/vaf_cutoff_experiment.Rmd:  install.packages("GGally")
snv-callers/vaf_cutoff_experiment.Rmd:  install.packages("ggupset")
```

**Comment by cansavvy** [comment]
`mutect2-vs-strelka2` is long retired and isn't run in CircleCI tests, do we still want to update it?

**Comment by cansavvy** [comment]
I started working on this with some of the notebooks I originally created, I can go ahead and remove the R package installations for all of these listed (and if I find any others).

**Comment by cbethell** [comment]
I have removed the package installation steps from `oncoprint-landscape/01-plot-oncoprint.R` in the open PR #666 (I can revert this change if we would prefer that these steps be removed all in one PR however).

**Comment by cansavvy** [comment]
@cbethell No need to change it. I will do multiple PRs for these anyway. I'll keep track of which modules are revised here as I open PRs for them.

**Comment by cansavvy** [comment]
Should I be ignoring deprecated/retired analyses, I assume?

**Comment by jaclyn-taroni** [comment]
What is the downside to fixing those? Lots of time to rerun I assume?

**Comment by cansavvy** [comment]
> What is the downside to fixing those? Lots of time to rerun I assume?

Yes but mainly I’m encountering other errors not related to `install.packages` due to data release changes that haven’t been fixed since they’ve been deprecated. So it will involved me fixing errors that are outside this issue.

**Comment by jaclyn-taroni** [comment]
Ah, makes sense - skip 'em!

**Comment by cansavvy** [comment]
Keeping track of the changes I make here as I do them. (TBD means I haven't gotten to it yet.)
| Module | Status | PR ref |
|--------|-------|--------|
| [`chromosomal-instability`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/chromosomal-instability) | No changes needed|   |
| [`cnv-chrom-plot`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/cnv-chrom) | Got rid of gistic_plot.Rmd:  `install.packages("BiocManager")` and `BiocManager::install("ggbio")` and refreshed |
| [`cnv-comparison`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/cnv-comparison) | Deprecated analysis -> skipped |
| [`collapse-rnaseq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/collapse-rnaseq) | No changes needed |
| [`comparative-RNASeq-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/comparative-RNASeq-analysis) | No changes needed |
| [`copy_number_consensus_call`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/copy_number_consensus_call) | No changes needed
| [`create-subset-files`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/create-subset-files) | No changes needed |
| [`focal-cn-file-preparation`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/focal-cn-file-preparation) | Got rid of series of installs in `04-prepare-cn-file.R` | TBD|
| [`fusion_filtering`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion_filtering) | TBD|TBD|
| [`fusion-summary`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/fusion-summary)| TBD|TBD|
| [`gene-set-enrichment-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gene-set-enrichment-analysis) | TBD|TBD|
| [`gistic-cohort-vs-histology-comparison`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/gistic-cohort-vs-histology-comparison) |TBD|TBD|
| [`immune-deconv`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv) |TBD|TBD|
| [`independent-samples`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/independent-samples) | TBD|TBD|
| [`interaction-plots`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/interaction-plots) | TBD|TBD|
| [`molecular-subtyping-ATRT`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-ATRT) | TBD|TBD|
| [`molecular-subtyping-EPN`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EPN) | TBD|TBD|
| [`molecular-subtyping-EWS`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-EWS) | TBD|TBD|
| [`molecular-subtyping-HGG`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-HGG) | TBD|TBD|
| [`molecular-subtyping-LGAT`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-LGAT)| TBD|TBD|
| [`molecular-subtyping-SHH-tp53`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-SHH-tp53) | Skipped because deprecated|NA|
| [`molecular-subtyping-chordoma`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-chordoma) |TBD|TBD|
| [`molecular-subtyping-embryonal`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-embryonal) |TBD|TBD|
| [`molecular-subtyping-pathology`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/molecular-subtyping-pathology) |TBD|TBD|
| [`mutational-signatures`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutational-signatures) |TBD|TBD|
| [`mutect2-vs-strelka2`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutect2-vs-strelka2) | Skipped because deprecated | NA|
| [`oncoprint-landscape`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/oncoprint-landscape) | TBD| TBD|
| [`rna-seq-composition`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/rna-seq-composition) | TBD| TBD|
| [`run-gistic`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/run-gistic) | TBD| TBD|
| [`sample-distribution-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/sample-distribution-analysis) | TBD| TBD|
| [`selection-strategy-comparison`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/selection-strategy-comparison) | TBD| TBD|
| [`sex-prediction-from-RNASeq`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/sex-prediction-from-RNASeq) |TBD| TBD|
| [`snv-callers`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/snv-callers) |TBD| TBD|
| [`ssgsea-hallmark`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/ssgsea-hallmark) | `pbta-gene-counts-rsem-expected_count.stranded.rds` | Skip because deprecated | TBD|
| [`sv-analysis`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/sv-analysis) |TBD| TBD|
| [`telomerase-activity-prediction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/telomerase-activity-prediction)| TBD| TBD|
| [`tmb-compare-tcga`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/tmb-compare-tcga) |TBD| TBD|
| [`tp53_nf1_score`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/tp53_nf1_score) |TBD| TBD|
| [`transcriptomic-dimension-reduction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/transcriptomic-dimension-reduction)| TBD| TBD|
| [`tcga-capture-kit-investigation`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/tcga-capture-kit-investigation) |TBD| TBD|
