### ISSUE TITLE
Update molecular subtyping file

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#702]
#### What data file(s) does this issue pertain to?
https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-pathology/results/compiled_molecular_subtypes_with_pathology_feedback.tsv

#### What release are you using?

NA

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Please add "Updated via OpenPBTA subtyping" to the Notes field for all rows in which subtypes were determined via OpenPBTA subtyping and perhaps "Updated via OpenPBTA subtyping and pathology assessment" (or similar) for tracking purposes.

cc @jaclyn-taroni and @baileyckelly

**Comment by jaclyn-taroni** [comment]
Do you have specific examples where the Notes column needs to be changed? Many rows already contain "Updated via OpenPBTA subtyping."

**Comment by jharenza** [comment]
Looks like LGG, for instance, are NA, but have been subtyped.

**Comment by jaclyn-taroni** [comment]
I will defer to @baileyckelly and @allisonheath, as I know there are changes to how the clinical file are being generated (#656). I find "Updated via OpenPBTA subtyping" ambiguous – it could mean that the histology label changed, it could mean the addition of a subtype label. That's why I left it off of LGG.

**Comment by jharenza** [comment]
updated in #854
