### ISSUE TITLE
Medulloblastoma pathology subtypes: file for data release

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#746]
#### What data file(s) does this issue pertain to?
A working GDoc of medulloblastoma subtypes being extracted from pathology reports [here](https://docs.google.com/spreadsheets/d/1lfEYhrKA2CJAKVTQVEvFRi2vj-1daUw4FGAehaHb358/edit#gid=0). 

#### What release are you using?

v16

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Column B was used for #743, but:
1. We will want a stable version of this file, rather than a google doc, so we should include in a future release
2. We found some data entry errors, these are undergoing re-review, and the results may change the accuracies for #743.

**Comment by jharenza** [comment]
cc @yuankunzhu just to be aware

**Comment by jaclyn-taroni** [comment]
While addressing #756, specifically making the switch to use `pathology_diagnosis` and `pathology_free_text_diagnosis` instead of `short_histology`, we now have a sample that was not originally included in `molecular-subtyping-MB` being subtyped (changed from `Medulloblastoma` -> `ETMR` in `molecular-subtyping-embryonal`) . The code in `analyses/molecular-subtyping-MB/03-compare-classes.Rmd` is tied closely to the structure of the expected classes file. 

In https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/787/commits/aea735ead26e05b21c2b2e0cb41a885688d6a9c3, I added a version of this file called `analyses/molecular-subtyping-MB/input/expected_class_v17.rds` with `NA` values in `pathology_subtype` and `other_molecular_findings` columns for this sample.

This additional sample should be taken into account as this issue is being addressed.

**Comment by jharenza** [comment]
That sample `BS_QWNBZ9RJ` was mistakenly entered as medulloblastoma into our database, but will add it to this list, and try to see if we can get that updated on the backend. Thanks!

**Comment by jharenza** [comment]
> That sample `BS_QWNBZ9RJ` was mistakenly entered as medulloblastoma into our database (path report had handwritten `medulloblastoma` but final dx was `ETMR`), but will add it to this list, and try to see if we can get that updated on the backend. Thanks!

@jaclyn-taroni as an update, we got this sample updated in our database, so with V18, its `pathology_diagnosis` will be `Other` with `ETMR` in `pathology_free_text_diagnosis`.

**Comment by jharenza** [comment]
File for release:
[openPBTA-mb-pathology-subtypes.csv](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6321102/openPBTA-mb-pathology-subtypes.csv)

Full notes for record-keeping:
[2021-04-15-openPBTA-mb-pathology-subtypes-full-notes.xlsx](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/6321112/2021-04-15-openPBTA-mb-pathology-subtypes-full-notes.xlsx)

**Comment by jharenza** [comment]
added in #1026

**Comment by jharenza** [comment]
This file is on aws, but is missed in `md5sum.txt` file, so we will add with v20.

**Comment by jharenza** [comment]
closed with #1118
