### ISSUE TITLE
molecular subtyping: BS_N6N147BY

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#783]
#### What data file(s) does this issue pertain to?
pbta-histologies.tsv

#### What release are you using?

V17

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

#### Put your question or report your issue here.
Found this sample had conflicting histology information:

| Kids_First_Biospecimen_ID | pathology_diagnosis                              | integrated_diagnosis                     | short_histology | broad_histology | pathology_free_text_diagnosis |
|---------------------------|--------------------------------------------------|------------------------------------------|-----------------|-----------------|-------------------------------|
| BS_N6N147BY               | High-grade glioma/astrocytoma (WHO grade III/IV) | Embryonal tumor with multilayer rosettes | ETMR            | Embryonal tumor | high-grade glioma             |

Looks like we should add `integrated_dx`, `broad_histology`, and `short_histology` to this table: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-embryonal/results/embryonal_tumor_molecular_subtypes.tsv

**Comment by jaclyn-taroni** [comment]
Putting this in the context of my understanding of the information on #748 - If this biospecimen was originally classified as HGG (`pathology_diagnosis`) and through the `molecular-subtyping-embryonal` module, but we classified this as ETMR, C19MC-altered (`molecular_subtype`) because of the presence of a _TTYH1_ fusion _and_ `integrated_diagnosis` and, as a result, `broad_histology` and `short_histology` are downstream of molecular subtyping - isn't what you've posted here what we would expect?

**Comment by jharenza** [comment]
Actually, yes, once #748 is completed, then we will expect to just do the subtyping here. I think I made this issue based on how the modules are currently set up, but they are being revamped now, so perhaps this is no longer relevant, but I think, also good to note, as this is an inaccuracy in the data as it stands. 

Do you think for all of the subtyping modules, we should then leave those 3 fields blank? We kept them in the last release so lack of those fields did not break anything.

**Comment by jharenza** [comment]
closing because we are now leaving those fields in the updated subtyping modules
