### ISSUE TITLE
Planned Analysis: Copy number plot showing recurrently amplified/deleted regions in different PBTA cancers

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#8]
The idea would be to visualize trends of deletions / amplifications in each of the cancer types (where relevant). Pointing out highly amplified/deleted regions with oncogenes/tumor suppressors may be interesting.

**Comment by cgreene** [comment]
@jharenza : is this still blocked? It seems like something that could be done now and if the CNV calls get improved, then this would just get re-run.

**Comment by jharenza** [comment]
> @jharenza : is this still blocked? It seems like something that could be done now and if the CNV calls get improved, then this would just get re-run.

I think I may have added it that way thinking consensus calls @gonzolgarcia creates would go into this, but perhaps consensus for CNV and SV would be separate issues?

**Comment by cbethell** [comment]
I have begun to tackle this issue. Thus far, I believe the package `GenVisR` would be useful for this issue based on the literature I found [here](https://genviz.org/module-03-genvisr/0003/05/01/cnFreq_GenVisR/). If there are any suggestions for the implementation of an alternative package, please feel free to express them here.

**Comment by jaclyn-taroni** [comment]
Related: #128

**Comment by jharenza** [comment]
Hi @cbethell ! Thanks for working on this! I also just created an issue #128 for creation of consensus calls for CN to improve our accuracy for downstream analytics like this issue. I previously have used [GISTIC](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3218867/), but it does not work well for small cohorts (ie you need a large N to call recurrence within a caner). We may want to focus this issue on histologies with a specified >= N so that we have enough power to detect recurrent changes already known in the literature. For example, we have a large cohort of low-grade gliomas, we have a good number of medulloblastomas (could see how many of each subtype we have since we know each subtype has different CNAs - [Figure 2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306779/)), high-grade gliomas. I found [this recent paper](https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0041082&type=printable) describing `TAGCNA`, which may work similar to GISTIC.

**Comment by jaclyn-taroni** [comment]
**Summarizing _my understanding_ of the status of this issue:**

* The mention of GISTIC and TAGCNA = I understand we're looking for significant amplifications or deletions and therefore some metric and test for significance. 

* As far as visualization is concerned, @jharenza has requested

  > having this plotted in GISTIC-type format for the different histologies or as an IGV-type figure, grouped by histology, would be most effective for showing recapitulation of previous findings. https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/142#issuecomment-544537440

  Here's an example from [Chekaluk et al.](https://doi.org/10.1371/journal.pone.0060927):

![](https://www.researchgate.net/profile/Chin-Lee_Wu/publication/236207718/figure/fig1/AS:299369854193679@1448386743605/GISTIC-plot-of-genomic-regions-with-CN-gain-or-loss-from-the-MIP-analysis-on-73.png)

* Once a consensus set of copy number calls has been generated (#128; output should still be a SEG file), we will want to examine results _by histology_ as specified by the title of this issue and https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/142#issuecomment-543448864. Medulloblastoma is a good starting point because we have prior knowledge about what CNAs to expect ([Figure 2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306779/figure/Fig2/) linked above by @jharenza).

* GISTIC files may be included in a later release (https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/142#issuecomment-544561686), but given the limitations of GISTIC, we would drop histologies with low numbers (https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/8#issuecomment-535018323). 

  If GISTIC files are included in a later release, we could use `maftools`, which is already on the Docker container, to produce plots: https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#8_processing_copy-number_data

* We could also try using TAGCNA as an alternative to GISTIC. It is an R package on sourceforge rather than CRAN or Bioconductor that does not appear to be actively maintained and appears to be less frequently used compared to GISTIC.

----

Also I would note if anyone is going to continue development prior to #128, probably use CNVkit and not ControlFREEC (see [caveat in README](https://github.com/AlexsLemonade/OpenPBTA-analysis#data-caveats) and the caveat in action in [this plot](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/c8a2399fb31e1024938c24693ed5fddc6343756f/analyses/cnv-comparison/plots/compare_cnv_output_barplot_aberration.pdf)).

**Comment by jaclyn-taroni** [comment]
GISTIC 2.0 is available as [a GenePattern module](http://software.broadinstitute.org/cancer/software/genepattern/modules/docs/GISTIC_2.0). This requires a reference file:

> Reference Genome File (-refgene) (REQUIRED) 
> The reference genome file contains information about the location of genes and cytobands on a given build of the genome. Reference genome files are created in MATLAB TM and are not viewable with a text editor. The GISTIC 2.0 release includes the following reference genomes: hg16.mat, hg17.mat, hg18.mat, and hg19.mat).

That description makes it seem like it might not be the most straightforward to obtain/derive?

Also requires:

> Markers File (-mk) (REQUIRED)
  The markers file identifies the marker names and positions of the markers in the original dataset (before segmentation). It is a three-column, tab-delimited file with an optional header. The column headers are:

    Marker Name (marker name)
    Chromosome (chromosome number)
    Marker Position (in bases)

I think if we could run this in something like [GenePattern Notebook](https://genepattern-notebook.org/) so it's something public facing we can link to in a README, that could be good. Alternatively, something publicly facing on CAVATICA that can be linked to in the same way.

This requires a little bit more research before we know if it's feasible but wanted to report what I know so far.

**Comment by jharenza** [comment]
@jaclyn-taroni I may be able to run this tomorrow and provide in the data release, once I get the updated seg files.

**Comment by cansavvy** [comment]
Did we want this plot to be exactly like [the example above](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/8#issuecomment-546625114)? Here is what I have so far: 
![Screen Shot 2019-12-13 at 11 55 48 AM](https://user-images.githubusercontent.com/23458084/70817413-86651b00-1d9f-11ea-9644-ecbce6561b84.png)

**Comment by cansavvy** [comment]
@jharenza , do you have thoughts about this rough draft GISTIC plot? What changes would you like to see?

**Comment by cansavvy** [comment]
Per @jharenza , I will update this graph to be split up by specific histologies and annotate the chromosomes more clearly, perhaps like this example: 
<img width="466" alt="Screen Shot 2019-12-19 at 2 17 15 PM" src="https://user-images.githubusercontent.com/23458084/71202588-8c10a400-226a-11ea-9c15-b9dd025c581c.png">

**Comment by cansavvy** [comment]
@jharenza It doesn't look like the GISTIC results are split up by histology or have scores by samples, so I won't be able to do the individually plots by histology unless you run it separately. That being said, here's a re-done version of the GISTIC plot with the other fixes. I can functionalize this and apply it to histology groups if we get that data. 
![gistic_plot](https://user-images.githubusercontent.com/23458084/71279627-377f2e80-2327-11ea-89b6-5d88503e633c.png)

**Comment by jharenza** [comment]
@cansavvy yeah, that's right - I can't really do it by histology because there will be too low of an N for many histologies. For that reason, what I had done in the past is just subset the samples from the seg file per each histology and plot LRR as in the NBL figure above, pointing out key regions of amp/del, so there was no statistical test for those plots. I wonder if there is a way to use GISTIC `all_data_by_genes.txt` or the chr arm data matrices to do enrichments? Otherwise, maybe we can focus on just the histologies with a certain N samples and I can rerun.

The plot looks better! Is there a way to scale by chr size such that chr 1 is the largest and 22 the smallest? Are 23 and 24 X and Y?

**Comment by cansavvy** [comment]
Ah good point, I’ll try to make the chromosomes scaled and change 23 and 24 to X and Y. I’ll look into making LRR plots by histology.

**Comment by cansavvy** [comment]
@jharenza , do you have code associated with [the graph above](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/8#issuecomment-567625912) That you would be able to send me so I can see how the y axis data was calculated?

**Comment by jharenza** [comment]
Hi @cansavvy - I added it [here](https://github.com/marislab/pptc-pdx-copy-number-and-SVs/blob/master/R/CN-plot-by-histology-revision.R) but could not get the `hg19.mat` added and able to read into R - I tried to add and change permissions - even if I moved it on my computer to be outside of the GISTIC program, I was unable to the read it into R. Strange... so, unfortunately, it seems the user will have to unpack GISTIC to get that file. Sent you another message about that.

**Comment by cansavvy** [comment]
@jharenza , Per our discussion in Slack, it appears the difference between the code you linked above (which used ControlFreeC) and our data we are using here (CNVKit derived) is that we do not have `Log R Ratios` calculated. This being said, what stat would we like to use instead to report a CNV summary for each histology group? Median copy number (using `copy.num` from the `CNVKit` seg file) seems like the simplest approach so I will use it as a stand in for now. 

I am not familiar with what is standard practice for reporting these data so if there is a preferred alternative to median copy number, let me know and I should be able to fairly easily switch out the calculation. I will look at some papers and see if I can figure out something better as well.

**Comment by cansavvy** [comment]
It appears that `Log R Ratio`/`LRR` that ControlFreeC gives is conceptually similar/equivalent to CNVKit's `seg.mean` column (See [CNVKit's docs](https://cnvkit.readthedocs.io/en/stable/fileformats.html)). We should probably add this revelation to the documentation and I will make an issue for that and for other CNV related data descriptions we may need to elaborate on. 

That being said I'm going to move forward with using `seg.mean` data and take some sort of average across samples of the same histology group.

**Comment by jaclyn-taroni** [comment]
We have a consensus SEG file that includes the `seg.mean` as of #441:

**Comment by cansavvy** [comment]
I believe this issue can be closed now?
