### ISSUE TITLE
Planned release: V19

### ISSUE THREAD

**Issue by jharenza** [AlexsLemonade/OpenPBTA-analysis#867]
#### What data file(s) does this issue pertain to?
`pbta-histologies.tsv`
all RNA-Seq files

#### What release are you using?

V18

#### Put a link to the relevant section of the [OpenPBTA-manuscript](https://github.com/AlexsLemonade/OpenPBTA-manuscript/) here.
NA

Remove BS_JXF8A2A6 from dataset per #862 
- [x] pbta-star-log-final.tar.gz
- [x] pbta-star-log-manifest.tsv
- [x] pbta-mend-qc-manifest.tsv
- [x] pbta-mend-qc-results.tar.gz
- [x] pbta-isoform-counts-rsem-expected_count.stranded.rds
- [x] pbta-isoform-expression-rsem-tpm.stranded.rds
- [x] pbta-fusion-arriba.tsv.gz
- [x] pbta-fusion-putative-oncogenic.tsv
- [x] pbta-fusion-recurrently-fused-genes-byhistology.tsv
- [x] pbta-fusion-recurrently-fused-genes-bysample.tsv
- [x] pbta-fusion-starfusion.tsv.gz
- [x] pbta-gene-counts-rsem-expected_count.stranded.rds
- [x] pbta-gene-expression-kallisto.stranded.rds
- [x] pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds
- [x] pbta-gene-expression-rsem-fpkm.stranded.rds
- [x] pbta-gene-expression-rsem-tpm.stranded.rds
- [x] independent-specimens.rnaseq.primary-plus-stranded.tsv
- [x] fusion_summary_lgat_foi.tsv
- [x] pbta-histologies-base.tsv
- [x] pbta-histologies.tsv
- [ ] md5sum.txt
 
Add new medulloblastoma subtype pathology results file #746

Update all molecular subtypes, broad_histologies, short_histologies, and integrated_diagnoses.

**Comment by jaclyn-taroni** [comment]
I am not sure that this issue is totally up to date, but I did want to make note of something that will need to be included in the v19 release. 

We anticipate that there will be new LGAT subtyping information that can be included in v19. One of the multiple LGAT subtyping pull requests (#842) was merged before v18 went out, but we did not want to hold up v18 for all of the LGAT pull request (see: https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/847#issuecomment-758011996). The results files going in as part of https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/896 will not include new LGAT subtyping information, but the code base will reflect that #842 went in.

**Comment by jharenza** [comment]
- Add PFS_days to histologies file per #963 
- Add hotspot + consensus SNV maf
- possibly update CNV files per #43 (TBD)
- Rerun all subtyping per #959 
- Add MB file needed for #747

**Comment by kgaonkar6** [comment]
Just documenting some file updates for the v19 release:

@migbro added updated maf files for pbta and tcga 
- [ ] pbta-tcga-snv-mutect2.vep.maf.gz
- [ ] pbta-tcga-snv-lancet.vep.maf.gz
- [ ] pbta-tcga-snv-strelka2.vep.maf.gz
- [ ] pbta-snv-lancet.vep.maf.gz
- [ ] pbta-snv-strelka2.vep.maf.gz
- [ ]  pbta-snv-mutect2.vep.maf.gz
- [ ] pbta-snv-vardict.vep.maf.gz

@jashapiro added the consensus files based on the updated MAFs to https://open-pbta.s3.us-east-1.amazonaws.com/data/snv-consensus/snv-consensus-20210427.zip. The files being updated are:
- [ ] pbta-snv-consensus-mutation.maf.tsv.gz
- [ ] pbta-snv-consensus-mutation-tmb-all.tsv
- [ ] pbta-snv-consensus-mutation-tmb-coding.tsv
- [ ] tcga-snv-consensus-snv.maf.tsv.gz
- [ ] tcga-snv-mutation-tmb-all.tsv
- [ ] tcga-snv-mutation-tmb-coding.tsv

**Comment by jharenza** [comment]
closed with #1026
