### ISSUE TITLE
v18 pbta-histologies.tsv has too many NAs for `short_histology` and `integrated_diagnosis`

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/OpenPBTA-analysis#875]
#### What data file(s) does this issue pertain to?

`pbta-histologies.tsv` from the v18 download. 

I've been trying to run things in CircleCI and a lot of things are breaking that we didn't expect (#874). 
As I've dug into these this morning I think I've realized that the big issue is that `short_histology` is mostly `NA`s but a lot of the code still uses `short_histology`. 

There are 1349 `NA`s out of 2845 rows. Was this expected? (for comparison v17 had 833 NAs for `short_histology`)

For example, ATRT doesn't run, because in the full `pbta-histologies.tsv` file, there are no ATRT samples in the `short_histology` column. 

This leads to 0 rows: 
```
  readr::read_tsv(file.path(root_dir, "data", "pbta-histologies.tsv"), guess_max = 10000) %>% 
  dplyr::filter(short_histology == "ATRT")
```

#### What release are you using?
v18 - I've checked out `jharenza:v18-files` and downloaded the data.

**Comment by cansavvy** [comment]
`broad_histology` has the same number of NAs (1349) in the same places as `short_histology`.

**Comment by cansavvy** [comment]
@kgaonkar6 , is this something you can look into?

**Comment by jashapiro** [comment]
Based on discussion in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870, and the [(prior) documentation](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#clinical-data-harmonization) it seems like `short_histology` is sometimes derived from `integrated_diagnosis`, but perhaps should now be derived from `harmonised_diagnosis`?

If we are going to be updating `short_histology` (or creating another indicator) I will again refer to https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/647, where I noted that the "Other" class in that field groups vastly disparate types which could be kept distinct quite easily.

**Comment by kgaonkar6** [comment]
The issue regarding the NAs was at the last step `molecular-subtype-integrate` module which was added as part of v18 release to add the subtyping to base histology.

I was only adding the subtyped broad_hist and short_hist instead of carrying over the original broad and short histology for samples that are not subtyped example ATRT. I've updated it as part of [018db25](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870/commits/018db25cd1dbdc61c7d468cef9622b2fa7f86d88) and added some additional checks.

@jashapiro  short_histology in v18 is directly mapped from pathology_diagnosis/pathology_free_text_diagnosis

```r
# pathology diagnosis is needed to match tumor samples  to broad/short histology
path_dx <- read_sheet('https://docs.google.com/spreadsheets/d/1fDXt_YODcSAWDvyI5ISBVhUCu4b5-TFCVWMOwiPeMwk/edit#gid=0',range="pathology_diagnosis_for_subtyping") %>%
   dplyr::select(pathology_diagnosis,broad_histology, short_histology) %>%
   write_tsv(file.path(input_dir,"pathology_diagnosis_for_subtyping.tsv"))

# pathology free text diagnosis is needed to match to samples marked as "Other" in pathology_diagnosis
path_free_text <- read_sheet('https://docs.google.com/spreadsheets/d/1fDXt_YODcSAWDvyI5ISBVhUCu4b5-TFCVWMOwiPeMwk/edit#gid=0',range="pathology_free_text_diagnosis_for_subtyping") %>%
   dplyr::select(pathology_free_text_diagnosis,broad_histology, short_histology)%>%
   write_tsv(file.path(input_dir,"pathology_free_text_diagnosis_for_subtyping.tsv"))
```

**Comment by jashapiro** [comment]
> short_histology in v18 is directly mapped from pathology_diagnosis/pathology_free_text_diagnosis

In that case, is the `short_histology` file now missing information it used to contain? Do we need to add another column with abbreviations for `harmonised_diagnosis` that we then use in its place for most analyses?

**Comment by kgaonkar6** [comment]
The missing short_histology values was an error in the code [molecular-subtype-integrate](https://github.com/kgaonkar6/OpenPBTA-analysis/tree/v18_int_dx_histology/analyses/molecular-subtyping-integrate) which I've now fixed with this : 

https://github.com/kgaonkar6/OpenPBTA-analysis/blob/227973887d924eaacf94b6f1a65dca6afe3d68d1/analyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd#L50-L59

<img width="483" alt="Screen Shot 2020-12-22 at 10 52 52 AM" src="https://user-images.githubusercontent.com/34580719/102907322-e4611f80-4443-11eb-9481-975e09c9a9ee.png">

From my understanding the short_histology is abbreviated harmonized_diagnosis since it's either integrated_diagnosis or pathology_diagnosis if integrated_diagnosis doesn't exist. 

But I guess you are right that short_histology  not abbreviated directly matching to harmonized_diagnosis for samples which are "Other" in pathology_diagnosis. harmonized_diagnosis is also "Other" as per decision above but short_histology is not actually abbreviated matching to term "Other" (it has the values from pathology_free_text_diagnosis)

**Comment by jashapiro** [comment]
@kgaonkar6 Thanks! That figure is helpful. Can you add where `harmonised_diagnosis` comes in? Is that the "molecular subtype integrate" step? 

To check my understanding, this means that broad and short histologies are in some sense "harmonised", as they are the "base" values _unless_ they have been updated by molecular subtyping? In a similar way that `harmonised_diagnosis` is the `pathology_diagnoisis` _unless_ `integrated_diagnosis` exists?

**Comment by cansavvy** [comment]
@kgaonkar6 I think the `md5sum.txt` file also needs to be updated in S3 -- currently it thinks the `md5sum.txt` fails for `pbta-histologies.tsv` but I suspect that is because the `md5sum.txt` file itself is out of date. We do expect `pbta-histologies.tsv` to be different than the old `md5sum.txt` file would suggest.

**Comment by kgaonkar6** [comment]
@cansavvy I did actually update the md5sum.txt as well. 
I had to delete the md5sum.txt in my existing local release-v18 folder and then run download_scrript.sh, I think that will help pass all checks.

**Comment by kgaonkar6** [comment]
> @kgaonkar6 Thanks! That figure is helpful. Can you add where `harmonised_diagnosis` comes in? Is that the "molecular subtype integrate" step?
> 
> To check my understanding, this means that broad and short histologies are in some sense "harmonised", as they are the "base" values _unless_ they have been updated by molecular subtyping? In a similar way that `harmonised_diagnosis` is the `pathology_diagnoisis` _unless_ `integrated_diagnosis` exists?

Right the harmonized_diagnosis comes in  "molecular subtype integrate" step.

And also correct that broad and short histology is harmonised similar to the way that harmonised_diagnosis is the pathology_diagnoisis unless integrated_diagnosis. 

But I think you are also right to be concerned that for samples with "Other" as harmonized_diagnosis it  doesn't directly abbreviate to "Other" since short and broad histology is mapped by pathology_free_text_diagnosis ( which are not harmonized or standard).

**Comment by cansavvy** [comment]
> @cansavvy I did actually update the md5sum.txt as well.
> I had to delete the md5sum.txt in my existing local release-v18 folder and then run download_scrript.sh, I think that will help pass all checks.

This worked. Thanks.

**Comment by jharenza** [comment]
> @kgaonkar6 Thanks! That figure is helpful. Can you add where `harmonised_diagnosis` comes in? Is that the "molecular subtype integrate" step?
> 
> To check my understanding, this means that broad and short histologies are in some sense "harmonised", as they are the "base" values _unless_ they have been updated by molecular subtyping? In a similar way that `harmonised_diagnosis` is the `pathology_diagnoisis` _unless_ `integrated_diagnosis` exists?

Hi @jashapiro - just to clarify. The `harmonized_diagnosis` is a new column. The other columns still exist. You can see [this comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870#pullrequestreview-550674561) which prompted adding the new column. In short, we add this at the last stage to not confuse the real definition of `integrated_diagnosis`, which means that the diagnosis comes from pathology + molecular data. Not all of our samples have an integrated diagnosis, so we added `harmonized_diagnosis` as the field with complete values for all tumors (either integrated or pathology diagnosis), whereas `integrated_diagnosis` now only contains true integrated diagnoses. 

Broad and short histologies are also base values unless updated by molecular subtyping, yes.

Thanks @kgaonkar6 for the diagram!

**Comment by cansavvy** [comment]
@kgaonkar6 It looks like `integrated_diagnosis has also lost a lot of information and now has `1586` `NA`s. In v17 there were `845` `NA`s for reference.

**Comment by kgaonkar6** [comment]
Here's the list of samples that have `new_hist[which(is.na(new_hist$integrated_diagnosis) & new_hist$sample_type=="Tumor"),]`
[NA_v18.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/5731487/NA_v18.txt)

To me it looks right, since these are either samples that we don't subtype OR we do subtype but we didn't find any molecular alteration to add to integrated_diagnosis. @jharenza @jaclyn-taroni thought? Do we want to update tsne analysis to use harmonized_diagnosis values or should we update the integrated_diagnosis?

**Comment by cansavvy** [comment]
> Here's the list of samples that have `new_hist[which(is.na(new_hist$integrated_diagnosis) & new_hist$sample_type=="Tumor"),]`
[NA_v18.txt](https://github.com/AlexsLemonade/OpenPBTA-analysis/files/5731487/NA_v18.txt)

And this is something new to v18 as compared to v17? So it would explain the increase in `NA`s?

**Comment by kgaonkar6** [comment]
I believe so, but will leave it to @jharenza  to clarify. 

`integrated_diagnosis` now only contains true molecular/pathology diagnosis values. Earlier we had some standardized values in `integrated_diagnosis` as well but now we have a new column `harmonized_diagnosis` to represent that standardization/harmonization as mentioned [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/875#issuecomment-749699294)

**Comment by cansavvy** [comment]
So do we suspect that in some places where `integrated_diagnosis` was being used for v17, we think should now be switched to `harmonized_diagnosis` for v18?

**Comment by jashapiro** [comment]
> So do we suspect that in some places where `integrated_diagnosis` was being used for v17, we think should now be switched to `harmonized_diagnosis` for v18?

I would bet that almost all downstream analyses that used `integrated_diagnosis` should be switched to `harmonized_diagnosis`, based on my understanding and the discussion in #870

**Comment by jharenza** [comment]
> > So do we suspect that in some places where `integrated_diagnosis` was being used for v17, we think should now be switched to `harmonized_diagnosis` for v18?
> 
> I would bet that almost all downstream analyses that used `integrated_diagnosis` should be switched to `harmonized_diagnosis`, based on my understanding and the discussion in #870

Yes, I think this is what we should do.

**Comment by jharenza** [comment]
closing as Nas for short histology were fixed per [this comment ](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/875#issuecomment-749621259) and are expected for integrated diagnosis per [this comment](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/875#issuecomment-749715406)
