### ISSUE TITLE
Updated analysis: Use `harmonized_diagnosis` instead of `integrated_diagnosis` in downstream analysis

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenPBTA-analysis#877]
#### What analysis module should be updated and why?

Possibly many, but I have not evaluated the extent yet. Certainly `interaction plots`, but other modules are likely involved.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

As discussed in #870, and illustrated in https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/870#issuecomment-749690672, as of v18, the `integrated_diagnosis` column is not longer the most complete column from which to get diagnosis information. Analyses that relied on it should be updated to use the more complete `harmonized_diagnosis`.

Some of these changes will likely be caught by #874 (which found `interaction plots`), but there may remain other modules that need updating.

#### What input data should be used? Which data were used in the version being updated?

v18

The first step will be to identify modules that need updating.

#### When do you expect the revised analysis will be completed?

Uncertain, probably should be broken into multiple issues.

#### Who will complete the updated analysis?

TBD

**Comment by cbethell** [comment]
It appears that the following files currently use `integrated_diagnosis`:

| Script                                           | Location                                |
|-----------------------|---------------------------------------------------------|
| `molecular-subtyping-HGG/00-HGG-select-pathology-dx.Rmd`       | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-HGG/00-HGG-select-pathology-dx.Rmd#L130 <br> We may want to add `harmonized_diagnosis` here rather than replace `integrated_diagnosis` |
| `molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd`      | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-LGAT/00-LGAT-select-pathology-dx.Rmd#L121 Again, we may want to add `harmonized_diagnosis` here rather than replace `integrated_diagnosis` |
| `molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd`             | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/53c1f7c8534d32da98c20f8e9136899e7dfcce92/analyses/molecular-subtyping-MB/00-mb-select-pathology-dx.Rmd#L58 `integrated_diagnosis` here is being used to filter to values = "Medulloblastoma", therefore we will likely want to replace it here with `harmonized_diagnosis` (should be re-run) |
| `molecular-subtyping-pathology/01-compile-subtyping-results.Rmd` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L161 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L188 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L206 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L230 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L251 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L270 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L291 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L308 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/01-compile-subtyping-results.Rmd#L329 <br> The purpose of this notebook is to aggregate molecular subtyping results into the column `integrated_diagnosis` so I believe this can stay as is but wanted to make a note of it here in case there are any objections. |
| `molecular-subtyping-pathology/02-incorporate-clinical-feedback.Rmd`    | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/molecular-subtyping-pathology/02-incorporate-clinical-feedback.Rmd#L178 <br> Again, I believe this can stay as is (it iterates on the above notebook) but wanted to make a note of it here in case there are any objections. |
| `molecular-subtyping-pathology/03-incorporate-pathology-feedback.Rmd`   | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/gene-set-enrichment-analysis/02-model-gsea.Rmd#L125 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/gene-set-enrichment-analysis/02-model-gsea.Rmd#L140 <br> Like the other notebooks in the `molecular-subtyping-pathology` module above, I believe this can stay as is but wanted to make a note of it here in case there are any objections. |
| `gene-set-enrichment-analysis/02-model-gsea.Rmd`    | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/gene-set-enrichment-analysis/02-model-gsea.Rmd#L24 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/7792a969784e5da6df52b02e23b05b9617c65bb8/analyses/gene-set-enrichment-analysis/02-model-gsea.Rmd#L140 <br> Note that these are the main instances that need to be replaced with `harmonized_diagnosis`, but changes should be propagated throughout the notebook (should to be re-run) |
| `sample-distribution-analysis/01-filter-across-types.R`     | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/01-filter-across-types.R#L32 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/01-filter-across-types.R#L56 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/01-filter-across-types.R#L58 <br> `integrated_diagnosis` here I believe should be replaced with `harmonized_diagnosis`, propagated throughout the notebook as only the main instances are noted here (notebook should be re-run) |
| `sample-distribution-analysis/02-multilayer-plots.R` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/02-multilayer-plots.R#L46 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/02-multilayer-plots.R#L48 <br> `integrated_diagnosis` here I believe should be replaced with `harmonized_diagnosis`, propagated throughout the notebook as only the first two/main instances are noted here (notebook should be re-run) |
| `sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L218 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L219 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/sample-distribution-analysis/03-tumor-descriptor-and-assay-count.Rmd#L231 <br> `integrated_diagnosis` here I believe should be replaced with `harmonized_diagnosis`and propagated throughout the notebook (should be re-run) |
| `interaction-plots/scripts/01-disease-specimen-lists.R`    | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/01-disease-specimen-lists.R#L67 <br> https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/01-disease-specimen-lists.R#L91 <br> `integrated_diagnosis` should be replaced with `harmonized_diagnosis` here (notebook should be re-run) |
| `interaction-plots/scripts/02-process_mutations.R` | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/02-process_mutations.R#L336 <br> `integrated_diagnosis` here I believe should be replaced with `harmonized_diagnosis` |
| `interaction-plots/scripts/03-plot_interactions.R`   | https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/ab673df68e4f10124f58463dbeb87ea4f800f9d5/analyses/interaction-plots/scripts/03-plot_interactions.R#L133 <br> If/when the other notebooks noted above in the `interaction-plots` module, the comment here should also be updated |

Note that I left a comment in parentheses for the instances above where I believe the notebook and/or module will need to be re-run once updated.
If I did not explicitly note that it should be re-run, it is because I believe it does not need to be based on results not being dependent on the update from `integrated_diagnosis` -> `harmonized_diagnosis`.

Also note that I plan to break up the table above into issues specific to each module to make this issue easier to tackle.
However, please feel free to leave any comments here or make any edits to this comment!

**Comment by cbethell** [comment]
Looks like this can be closed now that the last two PRs linked to/addressing this issue, #915 and #916, have been merged!
