### ISSUE TITLE
Planned Analysis: Unsupervised analysis of transcriptomic differences between different cancer types

### ISSUE THREAD

**Issue by PichaiRaman** [AlexsLemonade/OpenPBTA-analysis#9]
The idea is to demonstrate that samples in the PBTA cluster by cancer type / molecular subtype using a dimensionality reduction technique such as PCA/T-SNE/or UMAP. Please see figure 2 (https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1006599) as an example of using this to look at GTEx and differentiate different tissue types.

**Comment by jharenza** [comment]
Also consider Figure 3 in [this paper](https://www.ncbi.nlm.nih.gov/pubmed/30349086).

**Comment by cgreene** [comment]
![Screen Shot 2019-07-14 at 9 00 15 AM](https://user-images.githubusercontent.com/542643/61183946-d20b7100-a615-11e9-9212-e8f8cfc04600.png)

This is Figure 3 of the paper referenced by @jharenza.

I revised to remove the specific approach to figure generation so that we can have a discussion with folks who are interested in tackling this about what the preferred strategy is.

**Comment by cbethell** [comment]
I am beginning to flesh out the solution for this issue. If anyone has begun to work on it or have an idea of a preferred strategy, please feel free to express your thoughts.

**Comment by jaclyn-taroni** [comment]
As noted in the discussion on #116, we were planning on adding a README and 2 shell scripts to `analyses/transcriptomic-dimension-reduction`. I think we should hold off on that until #121 and #124 are completed @cbethell. We also need to decide if we will continue to include the plots that demonstrate the issue with the RNA library differences in that module or if we will remove that because we have @jashapiro's addition in #120 to serve that purpose.

**Comment by jaclyn-taroni** [comment]
Some initial work on this is currently in [`analyses/transcriptomic-dimension-reduction`](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/c8a2399fb31e1024938c24693ed5fddc6343756f/analyses/transcriptomic-dimension-reduction). For this reason, I am assigning this an `updated analysis` label.

**Comment by jaclyn-taroni** [comment]
Closing all planned analysis tickets in favor of opening new proposed analysis/updated analysis tickets as needed.
