### ISSUE TITLE
Help setting up docker and running collapse-rnaseq analysis

### ISSUE THREAD

**Issue by ajlee21** [AlexsLemonade/OpenPBTA-analysis#955]
#### What data file(s) does this issue pertain to?

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/collapse-rnaseq/run-collapse-rnaseq.sh
pbta-gene-expression-rsem-tpm.polya.rds
pbta-gene-expression-rsem-tpm.stranded.rds

#### Put your question or report your issue here.

Ultimately I am trying to get access to these files:
pbta-gene-expression-rsem-tpm.polya.rds
pbta-gene-expression-rsem-tpm.stranded.rds 

Looks like I need to run this bash script: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/collapse-rnaseq/run-collapse-rnaseq.sh

I performed the following steps to setup the docker image to run this file:
* Cloned this repo
* Install docker: https://docs.docker.com/buildx/working-with-buildx/
* Pull latest docker image: `docker pull ccdlopenpbta/open-pbta:latest`
* Run pre-built docker image: sudo docker run -e PASSWORD=password -p 8787:8787 -v myvol:/home/alexandra/Documents/Repos/OpenPBTA-analysis/analyses/collapse-rnaseq/ ccdlopenpbta/open-pbta:latest

At this point I can login into  R studio, but I am not sure how to run the bash script from within the docker image that is running.

This is my first time using docker so I'm sure there is something very basic I'm missing here.

Thank you for any help!

**Comment by jaclyn-taroni** [comment]
Hi @ajlee21!  

One thing you will want to do is attach the volume at the root of the repository so that you'll have access to the `data` directory on your local volume:

```
docker run -e PASSWORD=password -p 8787:8787 -v myvol:/home/alexandra/Documents/Repos/OpenPBTA-analysis ccdlopenpbta/open-pbta:latest
```

If you're able to log into RStudio, you can use the [RStudio Terminal](https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal) (if you see the `Console` where you'd execute your R code, it's to the right of that).

You'll need to navigate to the root of the repo on your local machine, which will be in `kitematic`, in that RStudio Terminal:

```sh
cd kitematic
```

And then you can run the bash script as "usual"

```sh
bash analyses/collapse-rnaseq/run-collapse-rnaseq.sh
```

Let me know if you have additional questions!

**Comment by jharenza** [comment]
Welcome, @ajlee21! The files are also available in the release downloads using the bash script in the main folder of the repo (instructions [here](https://github.com/AlexsLemonade/OpenPBTA-analysis#data-access-via-download-script)). Note: this will download _all_ data in the project.

We have also cloned these files in CAVATICA with the same structure of the release folders (see [here](https://github.com/AlexsLemonade/OpenPBTA-analysis#data-access-via-cavatica)) in case users only want select files. You would just have to set up a free account with CAVATICA and you then you can click the link and see the project.

**Comment by ajlee21** [comment]
Thank you both @jaclyn-taroni and @jharenza 

So I was playing around earlier using the RStudio terminal to try to navigate to `analyses/collapse-rnaseq/run-collapse-rnaseq.sh` but I got an error that it couldn't find the location.

I didn't think to look inside, `kitematic` but this directory appears empty for some reason. Perhaps I made a mistake on an earlier step...

**Comment by jaclyn-taroni** [comment]
> I didn't think to look inside, `kitematic` but this directory appears empty for some reason. Perhaps I made a mistake on an earlier step...

Okay, this is helpful info! It suggests to me that the volume step is causing trouble. I didn't notice earlier, but it doesn't look like you specify where the directory on your machine should "map to" in the container. 

Try navigating to the repo locally and running (this uses `--mount` instead of `--volume`):

```
docker run --mount type=bind,target=/home/rstudio/kitematic,source=$PWD -e PASSWORD=<password> -p 8787:8787 ccdlopenpbta/open-pbta:latest
```

**Comment by ajlee21** [comment]
> We have also cloned these files in CAVATICA with the same structure of the release folders (see [here](https://github.com/AlexsLemonade/OpenPBTA-analysis#data-access-via-cavatica)) in case users only want select files. You would just have to set up a free account with CAVATICA and you then you can click the link and see the project.

@jharenza I definitely read this response too quickly and misread this. Thank you for pointing me to this! Got the files!

Also @jaclyn-taroni Your suggestion is perfect and works! I'm glad I got to learn a bit about docker through this experience
